# Generated by Django 3.2.23 on 2024-03-07 10:36

from django.db import migrations, models
import hospital_operations.emr.models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0003_alter_medicalrecord_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='records',
        ),
        migrations.AddField(
            model_name='testresult',
            name='upload_results',
            field=models.FileField(blank=True, null=True, upload_to=hospital_operations.emr.models.get_upload_medRec),
        ),
    ]
