# Generated by Django 3.2.23 on 2024-03-07 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hospital_operations.emr.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emr', '0006_remove_testresult_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_results',
            field=models.FileField(blank=True, null=True, upload_to=hospital_operations.emr.models.get_upload_medRec),
        ),
        migrations.AddField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_test_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
