# Generated by Django 3.2.23 on 2024-03-08 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0009_auto_20240308_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
