# Generated by Django 3.2.23 on 2024-03-08 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0010_medicalrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
