# Generated by Django 3.2.23 on 2024-03-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0011_alter_medicalrecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='test_reults_signed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
