# Generated by Django 3.2.23 on 2024-03-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0012_testresult_test_reults_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test_reults_signed',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
