# Generated by Django 3.2.23 on 2024-03-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0015_auto_20240311_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='reference_ranges',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='units',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
