# Generated by Django 3.2.23 on 2024-02-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twofactorauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorauth',
            name='method',
        ),
        migrations.RemoveField(
            model_name='twofactorauth',
            name='secret',
        ),
    ]
