# Generated by Django 3.2.23 on 2024-02-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0001_push_notifications_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onesignalapp',
            name='author',
        ),
        migrations.AddField(
            model_name='onesignalapp',
            name='api_key',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onesignalapp',
            name='app_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onesignalapp',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
