# Generated by Django 3.2.23 on 2024-03-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='frm',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
