# Generated by Django 3.2.23 on 2024-03-05 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0002_auto_20240215_1753'),
        ('pharmacy', '0002_auto_20240305_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='notes',
        ),
        migrations.AlterField(
            model_name='medication',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management.product'),
        ),
    ]
