# Generated by Django 3.2.23 on 2024-03-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_auto_20240305_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='patient',
            new_name='user',
        ),
    ]
