# Generated by Django 3.2.23 on 2024-03-05 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_rename_patient_prescription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispense',
            name='dispense_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medication'),
        ),
        migrations.AlterField(
            model_name='dispense',
            name='quantity_dispensed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
