# Generated by Django 3.2.23 on 2024-02-15 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modules.hospital_operations.emr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_patientinfo_support_needed'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField()),
                ('doctor', models.CharField(max_length=100)),
                ('diagnosis', models.TextField()),
                ('symptoms', models.TextField()),
                ('tests_conducted', models.TextField()),
                ('medications_prescribed', models.TextField()),
                ('records', models.FileField(blank=True, null=True, upload_to=modules.hospital_operations.emr.models.get_upload_medRec)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='users.patientinfo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('test_name', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('reference_ranges', models.CharField(max_length=100)),
                ('result', models.CharField(max_length=100)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='emr.medicalrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
