# Generated by Django 3.2.23 on 2024-01-23 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('patient', 'Patient'), ('healthcare_provider', 'Healthcare Provider'), ('admin', 'Admin'), ('accountant', 'Accountant'), ('sales', 'Sales'), ('others', 'Others')], default='patient', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('age_range', models.CharField(blank=True, choices=[('18-29', '18-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50-59', '50-59'), ('60-69', '60-69'), ('70 and above', '70 and above')], max_length=255, null=True)),
                ('health_today', models.CharField(blank=True, choices=[('healthiest', "I'm the healthiest person I've ever been"), ('ok', "It's ok but could be better"), ('challenging', 'My health is challenging')], max_length=255, null=True)),
                ('busy_schedule', models.CharField(blank=True, choices=[('barely', 'Barely anytime for myself'), ('busy', "I'm busy but reserve some time for myself"), ('not_busy', "I'm not too busy")], max_length=255, null=True)),
                ('support_needed', models.CharField(blank=True, choices=[('immune_health', 'Improving immune health'), ('lose_weight', 'Losing weight'), ('reduce_stress', 'Reducing stress'), ('optimize_diet_exercise', 'Optimizing diet and exercise'), ('sleep_better', 'Sleeping better'), ('overall_wellness', 'Overall wellness')], max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
