# Generated by Django 3.2.23 on 2024-02-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
