# Generated by Django 3.2.23 on 2024-02-14 14:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinfo',
            name='support_needed',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('immune_health', 'Improving immune health'), ('lose_weight', 'Losing weight'), ('reduce_stress', 'Reducing stress'), ('optimize_diet_exercise', 'Optimizing diet and exercise'), ('sleep_better', 'Sleeping better'), ('overall_wellness', 'Overall wellness')], max_length=255, null=True),
        ),
    ]
