# Generated by Django 3.2.23 on 2024-02-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_patientinfo_support_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='blood_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='disability',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
