# Generated by Django 3.2.23 on 2024-02-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20240216_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='genotype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
