# Generated by Django 3.2.23 on 2024-02-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240229_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_days',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
