# Generated by Django 3.2.23 on 2024-02-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240229_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='experince',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
