# Generated by Django 3.2.23 on 2024-02-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_doctor_experince'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experince',
            new_name='experience',
        ),
    ]
