# Generated by Django 3.2.23 on 2024-03-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20240301_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='last_updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
