# Generated by Django 3.2.23 on 2024-03-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20240304_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consult_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
