# Generated by Django 3.2.23 on 2024-03-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_other_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='habits',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='physical_activity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='health_today',
            field=models.CharField(blank=True, choices=[('healthiest', "I'm the healthiest person I've ever been"), ('ok', "It's ok but could be better"), ('challenging', 'My health is challenging'), ('allergies_yes', 'Yes'), ('allergies_no', 'No'), ('medications_yes', 'Yes'), ('medications_no', 'No'), ('family_health_history_yes', 'Yes'), ('family_health_history_no', 'No')], max_length=255, null=True),
        ),
    ]
