# Generated by Django 3.2.23 on 2024-03-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20240307_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='allergies',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='family_health_history',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patientinfo',
            name='medications',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='patientinfo',
            name='health_today',
            field=models.CharField(blank=True, choices=[('healthiest', "I'm the healthiest person I've ever been"), ('ok', "It's ok but could be better"), ('challenging', 'My health is challenging')], max_length=255, null=True),
        ),
    ]
