# Generated by Django 3.2.23 on 2024-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20240307_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialized',
            field=models.TextField(blank=True, choices=[('dietician', 'dietician'), ('general_medicine_practitioner', 'General Medicine Practitioner'), ('geriatrician', 'Geriatrician')], max_length=255, null=True),
        ),
    ]
