# Generated by Django 3.2.23 on 2024-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_doctor_specialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialized',
            field=models.TextField(blank=True, choices=[('dietician', 'dietician'), ('general_medicine_practitioner', 'General Medicine Practitioner'), ('geriatrician', 'Geriatrician'), ('general_physician', 'General Physician'), ('mental_health', 'Mental Health'), ('practitioner', 'Practitioner'), ('ob_gyn', 'OB-GYN'), ('pt', 'Physical Therapy')], max_length=255, null=True),
        ),
    ]
