# Generated by Django 3.2.23 on 2024-03-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_doctor_specialized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialized',
            field=models.TextField(blank=True, choices=[('general_physician', 'General Physician'), ('mental_health', 'Mental Health'), ('practitioner', 'Practitioner'), ('ob_gyn', 'OB-GYN'), ('pt', 'Physical Therapy')], max_length=255, null=True),
        ),
    ]
