# Generated by Django 3.2.23 on 2024-03-22 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourite', models.CharField(blank=True, choices=[('1', 'Like'), ('0', 'Dislike')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_doctor_doctor', to='users.doctor')),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_doctor_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_doctor_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'doctor')},
            },
        ),
    ]
