# Generated by Django 3.2.23 on 2024-03-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20240319_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedoctor',
            name='action',
            field=models.CharField(blank=True, choices=[('1', 'Like'), ('0', 'Dislike')], max_length=255, null=True),
        ),
    ]
