# Generated by Django 3.2.23 on 2024-03-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_doctor_specialized'),
        ('users', '0028_likedoctor_action'),
    ]

    operations = [
    ]
